fixed linking problem with librecode:
$ gcc test.c -o test -lrecode -lc
/usr/lib/librecode.so: undefined reference to `xmalloc'
/usr/lib/librecode.so: undefined reference to `xrealloc'
collect2: ld returned 1 exit status

removed using internal xmallc/xrealloc wrappers for malloc/realloc which is
not linked with librecode. This wrapper is obsoleted and was only for
debugging. Patch posted to maintainer.

Changed files:
    recode-use_malloc_realloc.patch -> 1.1